### ISSUE TITLE
nodejs unit-http misses close()?

### ISSUE THREAD

**Issue by kbzowski** [nginx/unit#1061]
I have notice that during shutdown of NestJS based application which uses express internally I got an error:

```
TypeError: this.httpServer.close is not a function\n    at /app/server/node_modules/@nestjs/platform-express/adapters/express-adapter.js:96:55
   at new Promise .new Promise (<anonymous> undefined)
   at ExpressAdapter.close (/app/server/node_modules/@nestjs/platform-express/adapters/express-adapter.js:96:16 undefined)   
   at NestApplication.dispose (/app/server/node_modules/@nestjs/core/nest-application.js:47:53 undefined)
   at async process.cleanup (/app/server/node_modules/@nestjs/core/nest-application-context.js:189:1
```
Origin of the error is the close() function https://github.com/nestjs/nest/blob/master/packages/platform-express/adapters/express-adapter.ts#L160 which call http.close(). As far as I can see unit does not implement this function.

**Comment by tippexs** [comment]
Hi @kbzowski Sorry for the delayed response! @andrey-zelenkov Can you have a look at this, please as you have worked with some of the NodeJS fixes before.

**Comment by dbit-xia** [comment]
I also found that after `SIGINT`, the server's 'close' event will be automatically executed. For applications that require a graceful exit, it is advisable to support manual closure.

```
server.on('close', () => {
  console.log('server closed');
});
```
