### ISSUE TITLE
[error] 75#75 [unit] #10: the application returned not an iterable object

### ISSUE THREAD

**Issue by BwL1289** [nginx/unit#1236]
Hello,

Sorry in advance if this is a dumb question.

We just moved our monolithic Flask App from Lambda to Ecs Fargate w/ Nginx Unit.

Everything seems to be working except I am receiving the following error after the app starts, apis are registered, and the api call is processed successfully by the application:

```
2024/04/28 16:20:17 [error] 75#75 [unit] #10: the application returned not an iterable object
TypeError: 'NoneType' object is not iterable
```

This error is raised after we return a Flask `Response` object (`<Response 1548 bytes [200 OK]>`) or `json.dumps(...)` (the exit point of the app).

I see on this [line](https://github.com/nginx/unit/blob/master/src/python/nxt_python_wsgi.c#L418) the error is raised, but it's unclear to me how to mitigate this.

More context: for now, we're using wsgi protocol, and we proxy api calls to the relevant api and ultimately wrap Flask's `Response` object in a custom `Success` and `Error` classes as exit points.

Not sure if it's necessary to use `start_response` but I'm using it for good measure.

How can I further debug this?

**Comment by BwL1289** [comment]
Partially answering my own question but would sincerely appreciate input from the nginx unit team on how best to mitigate. Obviously, the `Response` object in Flask is not iterable, so the C call to `PyObject_GetIter` returns NULL and raises this error. 

I wonder if this should be classified as a bug or improvement then? 

Allowing users to migrate existing apps (that utilize `make_response` or return `Response` objects in Flask) makes nginx unit slightly harder to migrate to.

Guess I could just return the json prop of the `Response` obj like `json_resp.json`

**Comment by BwL1289** [comment]
This is WSGI. Here's an extremely dumbed down example. We are using `Flask_RESTful`, I don't know if that matters. What else can I provide to reproduce? 

```python
class JSONEncoder(json.JSONEncoder):
    def default(self, obj):
        try:
            if isinstance(obj, ObjectId):
                return str(obj)
            if isinstance(obj, datetime):
                return str(obj)
            return json.JSONEncoder.default(self, obj)
        except Exception as err:
            logger.exception(f"There was an error: {err}")
```

```python
class Response:
    @staticmethod
    def json(
        response: dict[str, Any],
        status_code: int,
        mimetype: str = "application/json",
    ) -> Any | None:
        json_resp = Response(
            response=json.dumps(response, cls=JSONEncoder),
            status=status_code,
            mimetype=mimetype,
        )

        logger.info(f"json: {json_resp.json}")

        return json_resp

class SuccessResponse(Response):
    def __new__(cls, payload: dict[str, Any] | None = None, status_code: int = 200) -> Response:
        response: dict[str, Any] = {"status": "success", "result": payload}
        return cls.json(response, status_code)
```

```python
def handler(unit_environ: dict[str, Any], unit_start_response) -> None:
    event_json = {}
    unit_start_response("200 OK", [("Content-Type", "application/json; charset=utf-8")])  # needed?
    lambda_handler(unit_environ, {})
```

```python
def get(self):
    try:
        found_organizations = {}
        num_org_records = len(found_organizations)
     except Exception as error:
        logger.exception(error)
        return ErrorResponse("Failed", error.args)
      else:
         return SuccessResponse({"records": found_organizations})
```

```json
{
  "listeners": {
    "*:80": {
      "pass": "applications/flask"
    }
  },

  "applications": {
    "flask": {
      "type": "python3",
      "path": "/www",
      "module": "app",
      "callable": "handler",
    }
  }
}
```

returns
```
{"level":"INFO","location":"json:32","message":"json: {'status': 'success', 'result': {'_id': 'omitted', 'email': ''omitted', 'updated_at': 'omitted, 'updated_by': ''omitted', 'name': ''omitted, 'picture': ''omitted.png', 'theme': 'light', 'is_admin': True}}
2024/04/28 20:02:52 [error] 73#73 [unit] #10: the application returned not an iterable object
TypeError: 'NoneType' object is not iterable
```

I also get this error if I just `json.dumps(...)` the actual json.

**Comment by ac000** [comment]
Hi,

I created a python file `gh1236.py` as

```python
import json;

class JSONEncoder(json.JSONEncoder):
    def default(self, obj):
        try:
            if isinstance(obj, ObjectId):
                return str(obj)
            if isinstance(obj, datetime):
                return str(obj)
            return json.JSONEncoder.default(self, obj)
        except Exception as err:
            logger.exception(f"There was an error: {err}")

class Response:
    @staticmethod
    def json(
        response: dict[str, Any],
        status_code: int,
        mimetype: str = "application/json",
    ) -> Any | None:
        json_resp = Response(
            response=json.dumps(response, cls=JSONEncoder),
            status=status_code,
            mimetype=mimetype,
        )

        logger.info(f"json: {json_resp.json}")

        return json_resp

class SuccessResponse(Response):
    def __new__(cls, payload: dict[str, Any] | None = None, status_code: int = 200) -> Response:
        response: dict[str, Any] = {"status": "success", "result": payload}
        return cls.json(response, status_code)

def handler(unit_environ: dict[str, Any], unit_start_response) -> None:
    event_json = {}
    unit_start_response("200 OK", [("Content-Type", "application/json; charset=utf-8")])  # needed?
    lambda_handler(unit_environ, {})

def get(self):
    try:
        found_organizations = {}
        num_org_records = len(found_organizations)
    except Exception as error:
        logger.exception(error)
        return ErrorResponse("Failed", error.args)
    else:
        return SuccessResponse({"records": found_organizations})
```

and a `gh1236.json` as

```json
{
    "listeners": {
        "[::1]:8080": {
            "pass": "applications/python"
        }
    },

    "applications": {
        "python": {
            "type": "python",
            "path": "/home/andrew/src/python",
            "module": "gh1236",
            "callable": "handler"
        }
    }
}
```

I had to `import json` but am still getting this error when trying to load it

```
2024/04/29 20:25:35 [alert] 4188#4188 Python failed to import module "gh1236"
Traceback (most recent call last):
  File "/home/andrew/src/python/gh1236.py", line 14, in <module>
    class Response:
  File "/home/andrew/src/python/gh1236.py", line 17, in Response
    response: dict[str, Any],
                        ^^^
NameError: name 'Any' is not defined. Did you mean: 'any'?
```
