### ISSUE TITLE
golang applications hang/segfault under Unit 1.4

### ISSUE THREAD

**Issue by plinss** [nginx/unit#172]
I have a number of microservice applications written in golang that work fine with Unit 1.3.

Upgrading to Unit 1.4 causes http requests to randomly hang and segfault.

Running Unit 1.4-2~stretch/amd64 and unit-go1.8 1.4-2~stretch/all on Debian with golang version go1.8.1 linux/amd64

From the unit.log:
```
        R
2018/10/04 11:40:09.039 [debug] 31820#31820 [unit] #59: GET /[obfuscated] (0)
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x78da3e]

goroutine 30 [running]:
runtime.throw(0x86d216, 0x5)
    /usr/lib/go-1.8/src/runtime/panic.go:596 +0x95 fp=0xc420022728 sp=0xc420022708
runtime.sigpanic()
    /usr/lib/go-1.8/src/runtime/signal_unix.go:297 +0x28c fp=0xc420022778 sp=0xc420022728
nginx/unit.nxt_go_request_handler.func1(0x4abd6cbd99041907, 0x720053d5f228ea7d, 0xc420070120)
    /usr/share/gocode/src/nginx/unit/request.go:134 +0x3e fp=0xc4200227c8 sp=0xc420022778
runtime.goexit()
    /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200227d0 sp=0xc4200227c8
created by nginx/unit.nxt_go_request_handler
    /usr/share/gocode/src/nginx/unit/request.go:136 +0x55

goroutine 1 [IO wait, locked to thread]:
net.runtime_pollWait(0x7f6301f01078, 0x72, 0xc4203f3898)
    /usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4202b3e28, 0x72, 0x100, 0x0)
    /usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4202b3e28, 0x7ffe6d4c9430, 0x1000)
    /usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).readMsg(0xc4202b3dc0, 0x7ffe6d4c9430, 0x1000, 0x1000, 0x7ffe6d4c9330, 0x100, 0x100, 0xffffffffffffffff, 0x0, 0x0, ...)
    /usr/lib/go-1.8/src/net/fd_unix.go:304 +0x21a
net.(*UnixConn).readMsg(0xc42000e0d0, 0x7ffe6d4c9430, 0x1000, 0x1000, 0x7ffe6d4c9330, 0x100, 0x100, 0x7b830dc138486701, 0x7b0000c4200b4878, 0x1, ...)
    /usr/lib/go-1.8/src/net/unixsock_posix.go:115 +0x91
net.(*UnixConn).ReadMsgUnix(0xc42000e0d0, 0x7ffe6d4c9430, 0x1000, 0x1000, 0x7ffe6d4c9330, 0x100, 0x100, 0xc9c6a0, 0x7f6301f5c000, 0x0, ...)
    /usr/lib/go-1.8/src/net/unixsock.go:131 +0xaa
nginx/unit.nxt_go_port_recv(0x7c4c, 0x7ffe6d4c9430, 0x1000, 0x7ffe6d4c9330, 0x100, 0x0)
    /usr/share/gocode/src/nginx/unit/port.go:163 +0x119
nginx/unit._cgoexpwrap_d050fa50fc84_nxt_go_port_recv(0x7c4c, 0x7ffe6d4c9430, 0x1000, 0x7ffe6d4c9330, 0x100, 0x24)
    nginx/unit/_obj/_cgo_gotypes.go:263 +0x55
nginx/unit._Cfunc_nxt_cgo_run(0xc420107f18, 0x0)
    nginx/unit/_obj/_cgo_gotypes.go:193 +0x4d
nginx/unit.ListenAndServe(0xc420011620, 0xe, 0xc68ec0, 0xc9b660, 0x1, 0xc420107f68)
    /usr/share/gocode/src/nginx/unit/unit.go:95 +0x39
main.main()
    /var/www/goalong/src/services/media/media.go:221 +0x17d

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
    /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1
```

In addition, in case it's relevant, when re-compiling the apps with unit 1.4 installed I get the following compiler warnings (the same apps compile warning free under Unit 1.3):

```
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c: In function ‘nxt_lvlhsh_bucket_find’:
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:146:5: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     (void *) (e)[0]
     ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:268:29: note: in expansion of macro ‘nxt_lvlhsh_entry_value’
                     value = nxt_lvlhsh_entry_value(e);
                             ^~~~~~~~~~~~~~~~~~~~~~
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c: In function ‘nxt_lvlhsh_new_bucket’:
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:151:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     (e)[0] = (uint32_t) n
              ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:319:9: note: in expansion of macro ‘nxt_lvlhsh_set_entry_value’
         nxt_lvlhsh_set_entry_value(bucket, lhq->value);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c: In function ‘nxt_lvlhsh_bucket_insert’:
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:146:5: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     (void *) (e)[0]
     ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:396:29: note: in expansion of macro ‘nxt_lvlhsh_entry_value’
                     value = nxt_lvlhsh_entry_value(e);
                             ^~~~~~~~~~~~~~~~~~~~~~
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:151:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     (e)[0] = (uint32_t) n
              ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:404:29: note: in expansion of macro ‘nxt_lvlhsh_set_entry_value’
                             nxt_lvlhsh_set_entry_value(e, new_value);
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:151:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     (e)[0] = (uint32_t) n
              ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:446:9: note: in expansion of macro ‘nxt_lvlhsh_set_entry_value’
         nxt_lvlhsh_set_entry_value(vacant_entry, lhq->value);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c: In function ‘nxt_lvlhsh_convert_bucket_to_level’:
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:146:5: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     (void *) (e)[0]
     ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:515:19: note: in expansion of macro ‘nxt_lvlhsh_entry_value’
         q.value = nxt_lvlhsh_entry_value(e);
                   ^~~~~~~~~~~~~~~~~~~~~~
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c: In function ‘nxt_lvlhsh_bucket_convertion_insert’:
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:151:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     (e)[0] = (uint32_t) n
              ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:592:13: note: in expansion of macro ‘nxt_lvlhsh_set_entry_value’
             nxt_lvlhsh_set_entry_value(e, lhq->value);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c: In function ‘nxt_lvlhsh_bucket_delete’:
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:146:5: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     (void *) (e)[0]
     ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:727:29: note: in expansion of macro ‘nxt_lvlhsh_entry_value’
                     value = nxt_lvlhsh_entry_value(e);
                             ^~~~~~~~~~~~~~~~~~~~~~
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:151:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     (e)[0] = (uint32_t) n
              ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:737:29: note: in expansion of macro ‘nxt_lvlhsh_set_entry_value’
                             nxt_lvlhsh_set_entry_value(e, NULL);
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c: In function ‘nxt_lvlhsh_bucket_each’:
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:146:5: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     (void *) (e)[0]
     ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:866:13: note: in expansion of macro ‘nxt_lvlhsh_entry_value’
     value = nxt_lvlhsh_entry_value(bucket);
             ^~~~~~~~~~~~~~~~~~~~~~
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c: In function ‘nxt_lvlhsh_bucket_peek’:
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:146:5: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     (void *) (e)[0]
     ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:975:13: note: in expansion of macro ‘nxt_lvlhsh_entry_value’
     value = nxt_lvlhsh_entry_value(entry);
             ^~~~~~~~~~~~~~~~~~~~~~
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:151:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     (e)[0] = (uint32_t) n
              ^
/usr/share/gocode/src/nginx/unit/nxt_lvlhsh.c:986:13: note: in expansion of macro ‘nxt_lvlhsh_set_entry_value’
             nxt_lvlhsh_set_entry_value(entry, NULL);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by mar0x** [comment]
Hi Peter,

Thanks for reporting!
This is the packaging issue and warnings are relevant and helped to understand the root of the issue.

The thing is go package contains sources and (wrongly) treated as platform-independent. This is wrong because it contains `nxt_auto_config.h` header file which is generated by configure script and contains platform-dependent macro definitions. Current package contains `nxt_auto_config.h` for 32bit platform.

While we fixing our packages you may try to build go package from sources. Here is the link for documentation page: http://unit.nginx.org/installation/#source-code . Exact configure options can be obtained from binary using: /usr/sbin/unitd --version . Building unit binaries is not required, only go package. Consider downloading source tarball https://unit.nginx.org/download/unit-1.4.tar.gz to use exact version.
```
$ curl https://unit.nginx.org/download/unit-1.4.tar.gz
$ tar -xzf unit-1.4.tar.gz
$ ./configure --prefix=/usr --state=/var/lib/unit --control=unix:/var/run/control.unit.sock --pid=/var/run/unit.pid --log=/var/log/unit.log --tests --openssl --modules=/usr/lib/unit/modules --cc-opt='-g -O2 -fdebug-prefix-map=/data/builder/debuild/unit-1.4/pkg/deb/debuild/unit-1.4=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --ld-opt='-specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'
```
You already may copy `sudo cp build/nxt_auto_config.h /usr/share/gocode/src/nginx/unit/` and re-build your go application or continue with complete go package installation:
```
$ ./configure go --go-path=/usr/share/gocode
$ sudo make go-install
```

Best regards,
Max

**Comment by plinss** [comment]
Friendly ping, this is still an issue with 1.6

**Comment by VBart** [comment]
@plinss Sorry for the delay. The task of converting Go package into architecture dependant is scheduled and I hope will be resolved soon.

**Comment by plinss** [comment]
Thanks for the update @Vbart, please note that I did try Max's instructions above and was able to get my services to build cleanly (golang v1.10 and Unit 1.6), however the original issue of the connection randomly hanging is still present.

I suspect there's a different issue causing the hangs.

**Comment by VBart** [comment]
Yes, it's a different issue.

@mar0x  Could you look at the connections hanging problem unrelated to our Go-packages?

**Comment by plinss** [comment]
Here's the unit.log output of a process that hung (note that the hangs are intermittent):

```
2018/11/29 13:56:00 Listening on 127.0.0.1:8003
2018/11/29 13:56:00.392 [debug] 94574#94574 epoll_wait(3): 1
2018/11/29 13:56:00.392 [debug] 94574#94574 epoll: fd:8 ev:0001 d:56011FB49B90 rd:5 wr:0
2018/11/29 13:56:00.392 [debug] 94574#94574 timer expire minimum: 2949964272:2863564520
2018/11/29 13:56:00.392 [debug] 94574#94574 work queue: fast
2018/11/29 13:56:00.392 [debug] 94574#94574 recvmsg(8, -1, 2): 16
2018/11/29 13:56:00.392 [debug] 94574#94574 port 8: message type:12
2018/11/29 13:56:00.392 [debug] 94574#94574 pthread_mutex_lock(56011FB3C2A0) enter
2018/11/29 13:56:00.392 [debug] 94574#94574 pthread_mutex_unlock(56011FB3C2A0) exit
2018/11/29 13:56:00.392 [debug] 94574#94574 process 96362 ready
2018/11/29 13:56:00.392 [debug] 94574#94574 new port 19 for process 96362
2018/11/29 13:56:00.392 [debug] 94574#94574 malloc(136): 56011FB54340
2018/11/29 13:56:00.392 [debug] 94574#94574 posix_memalign(128, 1024): 56011FB53300
2018/11/29 13:56:00.392 [debug] 94574#94574 mp 56011FB3D2A0 retain: 2
2018/11/29 13:56:00.392 [debug] 94574#94574 send port 19 to process 94582
2018/11/29 13:56:00.392 [debug] 94574#94574 pthread_mutex_lock(56011FB50A88) enter
2018/11/29 13:56:00.392 [debug] 94574#94574 using plain mode
2018/11/29 13:56:00.392 [debug] 94574#94574 sendbuf: 0, 56011FB53378, 32
2018/11/29 13:56:00.392 [debug] 94574#94574 sendmsg(13, 19, 2): 48
2018/11/29 13:56:00.392 [debug] 94574#94574 pthread_mutex_unlock(56011FB50A88) exit
2018/11/29 13:56:00.392 [debug] 94574#94574 recvmsg(8, -1, 2): -1
2018/11/29 13:56:00.392 [debug] 94574#94574 recvmsg(8) not ready
2018/11/29 13:56:00.392 [debug] 94574#94574 epoll 3 set event: fd:8 op:3 ev:80002001
2018/11/29 13:56:00.392 [debug] 94574#94574 work queue: fast
2018/11/29 13:56:00.392 [debug] 94574#94574 buf ts completion: 56011FB53300 56011FB53378
2018/11/29 13:56:00.392 [debug] 94574#94574 free(56011FB54340)
2018/11/29 13:56:00.392 [debug] 94574#94574 free(56011FB53300)
2018/11/29 13:56:00.392 [debug] 94574#94574 mp 56011FB3D2A0 release: 1
2018/11/29 13:56:00.392 [debug] 94574#94574 epoll 3 changes:1
2018/11/29 13:56:00.392 [debug] 94574#94574 epoll_ctl(3): fd:8 op:3 ev:80002001
2018/11/29 13:56:00.392 [debug] 94574#94574 epoll_wait(3) timeout:-1
2018/11/29 13:56:00.392 [debug] 94582#94582 epoll_wait(3): 1
2018/11/29 13:56:00.392 [debug] 94582#94582 epoll: fd:10 ev:0001 d:56011FB509E0 rd:5 wr:0
2018/11/29 13:56:00.392 [debug] 94582#94582 timer expire minimum: 2949964272:2863564520
2018/11/29 13:56:00.392 [debug] 94582#94582 work queue: fast
2018/11/29 13:56:00.392 [debug] 94582#94582 recvmsg(10, 28, 2): 48
2018/11/29 13:56:00.392 [debug] 94582#94582 port 10: message type:10
2018/11/29 13:56:00.392 [debug] 94582#94582 new port 28 received for process 96362:0
2018/11/29 13:56:00.392 [debug] 94582#94582 process port (96362, 0) not found
2018/11/29 13:56:00.392 [debug] 94582#94582 pthread_mutex_lock(56011FB3C2A0) enter
2018/11/29 13:56:00.392 [debug] 94582#94582 pthread_mutex_init(56011FB7A830)
2018/11/29 13:56:00.392 [debug] 94582#94582 pthread_mutex_init(56011FB7A868)
2018/11/29 13:56:00.392 [debug] 94582#94582 pthread_mutex_init(56011FB7A8A0)
2018/11/29 13:56:00.392 [debug] 94582#94582 process 96362 insert
2018/11/29 13:56:00.392 [debug] 94582#94582 pthread_mutex_unlock(56011FB3C2A0) exit
2018/11/29 13:56:00.392 [debug] 94582#94582 malloc(168): 56011FB55460
2018/11/29 13:56:00.392 [debug] 94582#94582 posix_memalign(16, 392): 56011FB7CE30
2018/11/29 13:56:00.392 [debug] 94582#94582 malloc(136): 56011FB55100
2018/11/29 13:56:00.392 [debug] 94582#94582 posix_memalign(128, 1024): 56011FB7D000
2018/11/29 13:56:00.392 [debug] 94582#94582 pthread_mutex_init(56011FB7CED8)
2018/11/29 13:56:00.392 [debug] 94582#94582 port 56011FB7CE30 96362:0 new, type 4
2018/11/29 13:56:00.392 [debug] 94582#94582 posix_memalign(16, 1320): 56011FB7D410
2018/11/29 13:56:00.392 [debug] 94582#94582 posix_memalign(16, 1000): 56011FB7D940
2018/11/29 13:56:00.392 [debug] 94582#94582 free(56011FB55380)
2018/11/29 13:56:00.392 [debug] 94582#94582 rpc: stream #51 last handler, type 10
2018/11/29 13:56:00.392 [debug] 94582#94582 pthread_mutex_lock(56011FB64860) enter
2018/11/29 13:56:00.392 [debug] 94582#94582 pthread_mutex_unlock(56011FB64860) exit
2018/11/29 13:56:00.392 [debug] 94582#94582 app 'traveler' new port ready, pid 96362, 3/0
2018/11/29 13:56:00.392 [debug] 94582#94582 pthread_mutex_lock(56011FB64860) enter
2018/11/29 13:56:00.392 [debug] 94582#94582 pthread_mutex_unlock(56011FB64860) exit
2018/11/29 13:56:00.392 [debug] 94582#94582 app 'traveler' 56011FB64860 requests queue is empty, keep the port
2018/11/29 13:56:00.392 [debug] 94582#94582 rpc: stream #51 free registration
2018/11/29 13:56:00.392 [debug] 94582#94582 recvmsg(10, -1, 2): -1
2018/11/29 13:56:00.392 [debug] 94582#94582 recvmsg(10) not ready
2018/11/29 13:56:00.392 [debug] 94582#94582 epoll 3 set event: fd:10 op:3 ev:80002001
2018/11/29 13:56:00.392 [debug] 94582#94582 epoll 3 changes:1
2018/11/29 13:56:00.392 [debug] 94582#94582 epoll_ctl(3): fd:10 op:3 ev:80002001
2018/11/29 13:56:00.392 [debug] 94582#94582 epoll_wait(3) timeout:-1
2018/11/29 13:57:00.115 [debug] 94582#95374 epoll_wait(15): 1
2018/11/29 13:57:00.115 [debug] 94582#95374 *36 epoll: fd:44 ev:2001 d:7F7D7C004260 rd:2 wr:0
2018/11/29 13:57:00.115 [debug] 94582#95374 timer expire minimum: 2949964240:2863624243
2018/11/29 13:57:00.115 [debug] 94582#95374 epoll_wait(15) timeout:-1
```

And for reference:
```
$ unitd --version
unit: [debug] sys_nerr: 132
unit: [debug] malloc(6820): 5628FECA5420
unit: [debug] stderr flags: 0x8402
unit: [debug] ncpu: 1
unit: [debug] pagesize: 4096
unit: [debug] malloc(24): 5628FECA6ED0
unit: [debug] malloc(1991): 5628FECA6EF0
unit: [debug] malloc(200): 5628FECA76C0
2018/11/29 13:59:31.606 [debug] 96762#96762 realloc(0, 32): 5628FECA7840
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(24): 5628FECA7930
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(168): 5628FECA7790
2018/11/29 13:59:31.606 [debug] 96762#96762 posix_memalign(16, 496): 5628FECA7950
2018/11/29 13:59:31.606 [debug] 96762#96762 pthread_mutex_init(5628FECA79C0)
2018/11/29 13:59:31.606 [debug] 96762#96762 posix_memalign(16, 832): 5628FECA7B50
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(136): 5628FECA7EA0
2018/11/29 13:59:31.606 [debug] 96762#96762 posix_memalign(128, 1024): 5628FECA7F80
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(1368): 5628FECA8390
2018/11/29 13:59:31.606 [debug] 96762#96762 create engine 5628FECA8390
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(16368): 5628FECA91F0
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(16368): 5628FECAD1F0
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(160): 5628FECA88F0
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(2048): 5628FECB11F0
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(384): 5628FECB1A00
2018/11/29 13:59:31.606 [debug] 96762#96762 epoll_create(): 3
2018/11/29 13:59:31.606 [debug] 96762#96762 signalfd(): 4
2018/11/29 13:59:31.606 [debug] 96762#96762 eventfd(): 5
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(2048): 5628FECB1B90
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(168): 5628FECA89A0
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(136): 5628FECB23A0
2018/11/29 13:59:31.606 [debug] 96762#96762 posix_memalign(128, 1024): 5628FECB2480
2018/11/29 13:59:31.606 [debug] 96762#96762 malloc(232): 5628FECB28F0
unit version: 1.6
configured as ./configure --debug --prefix=/usr --state=/var/lib/unit --control=unix:/var/run/control.unit.sock --pid=/var/run/unit.pid --log=/var/log/unit.log --modules=/usr/lib/unit/modules

```

**Comment by mar0x** [comment]
I'm sorry, but this information is not enough to find and fix the issue. Complete much unit.log is much more usable.

**Comment by tippexs** [comment]
Closed due to timeout
