### ISSUE TITLE
Unable to install npm package

### ISSUE THREAD

**Issue by xivistudios** [nginx/unit#189]
#npm i -g unit-http

> unit-http@1.6.0 install /usr/local/src/unit-bin/usr/local/lib/node_modules/unit-http
> node-gyp configure build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.9.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/src/unit-bin/usr/local/lib/node_modules/unit-http/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/src/unit-bin/usr/local/lib/node_modules/unit-http/.node-gyp'
gyp ERR! System Linux 4.4.0-139-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/src/unit-bin/usr/local/lib/node_modules/unit-http
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unit-http@1.6.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unit-http@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-25T12_12_07_882Z-debug.log

**Comment by VBart** [comment]
The `--unsafe-perm` option is required in your case:
```
# npm i -g --unsafe-perm unit-http
```

**Comment by xivistudios** [comment]
This option does not work for me.
```ssh
# npm i -g --unsafe-perm unit-http

> unit-http@1.6.0 install /usr/local/lib/node_modules/unit-http
> node-gyp configure build

make: Entering directory '/usr/local/lib/node_modules/unit-http/build'
  CXX(target) Release/obj.target/unit-http/unit.o
../unit.cpp: In function ‘void nxt_uv_read_callback(uv_poll_t*, int, int)’:
../unit.cpp:358:5: error: ‘nxt_unit_run_once’ was not declared in this scope
     nxt_unit_run_once((nxt_unit_ctx_t *) handle->data);
     ^~~~~~~~~~~~~~~~~
../unit.cpp:358:5: note: suggested alternative: ‘nxt_unit_buf_free’
     nxt_unit_run_once((nxt_unit_ctx_t *) handle->data);
     ^~~~~~~~~~~~~~~~~
     nxt_unit_buf_free
unit-http.target.mk:100: recipe for target 'Release/obj.target/unit-http/unit.o' failed
make: *** [Release/obj.target/unit-http/unit.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/unit-http/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.4.0-17134-Microsoft
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/unit-http
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unit-http@1.6.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unit-http@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-25T23_45_31_198Z-debug.log
```

**Comment by xivistudios** [comment]
I used the method in the official documentation to install the default latest binary distribution in Ubuntu.

```ssh
~ apt-key add nginx_signing.key
# Create the /etc/apt/sources.list.d/unit.list file For Ubuntu 16.04.
deb https://packages.nginx.org/unit/ubuntu/ xenial unit
deb-src https://packages.nginx.org/unit/ubuntu/ xenial unit
~ apt-get update
~ apt-get install unit
~ apt-get install unit-dev
```

**Comment by VBart** [comment]
@xivistudios please try updating your packages:
```apt-get update
apt-get upgrade```
