### ISSUE TITLE
Add connection object to unit http request

### ISSUE THREAD

**Issue by academici** [nginx/unit#232]
When nodejs server start with fastify, needed connection object
```bash
TypeError: Cannot read property 'remoteAddress' of undefined
    at _ipAsRemoteAddress (/home/vostrikov/site/frontend/node_modules/fastify/fastify.js:281:29)
    at Object.routeHandler [as handler] (/home/vostrikov/site/frontend/node_modules/fastify/fastify.js:303:5)
    at Router.lookup (/home/vostrikov/site/frontend/node_modules/find-my-way/index.js:338:14)
    at Server.createServer (/home/vostrikov/site/frontend/server.js:36:5)
    at Server.emit (events.js:189:13)
    at Server.emit_events (/usr/lib/node_modules/unit-http/http_server.js:382:12)
```

This script is works, can add to the documentation
```js
const { createServer, IncomingMessage, ServerResponse } = require("unit-http");

require("http").ServerResponse = ServerResponse;
require("http").IncomingMessage = IncomingMessage;

const serverFactory = (handler, opts) => {
  const server = createServer((req, res) => {
    req.connection = {};
    req.connection.remoteAddress = '127.0.0.1';
    handler(req, res);
  });
  return server;
};

const fastify = require("fastify")({ serverFactory });

fastify.get("/", (req, reply) => {
  reply.send({ hello: "world" });
});

fastify.get("/test", (req, reply) => {
  reply.send({ hello: "test" });
});

fastify.ready();
```

**Comment by mar0x** [comment]
Thank you! This is very helpful, maybe we should add this to our nodejs module.
