### ISSUE TITLE
[go] app crashes when benchmarking

### ISSUE THREAD

**Issue by tiago4orion** [nginx/unit#309]
The simple program below:

```
package main

import (
	"fmt"
	"log"
	"net/http"

	"nginx/unit"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World\n")
}

func main() {
	fmt.Println("Unit Example started")

	http.HandleFunc("/", handler)
	log.Fatal(unit.ListenAndServe(":65432", nil))
}
```

Crashes with a `SIGSEGV` when using a common benchmark tool:

```
$ ab -n 1000 -c 100 http://localhost:60000/
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
apr_socket_recv: Connection refused (111)
Total of 777 requests completed
```
Sometimes requires 2 or 3 runs to reproduce.

The crash log is below:

```
2019/09/10 08:10:42.275 [warn] 24134#24137 [unit] #747: add_field: too many response fields
unexpected fault address 0x7f372b567611
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f372b567611 pc=0x45bd5e]

goroutine 1 [running, locked to thread]:
runtime.throw(0x6f7b13, 0x5)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0000a1c20 sp=0xc0000a1bf0 pc=0x42ee92
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:397 +0x401 fp=0xc0000a1c50 sp=0xc0000a1c20 pc=0x4432b1
runtime.memmove(0xc000108000, 0x7f372b567611, 0xa5)
	/usr/local/go/src/runtime/memmove_amd64.s:213 +0x1de fp=0xc0000a1c58 sp=0xc0000a1c50 pc=0x45bd5e
runtime.gostringn(0x7f372b567611, 0xa5, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:328 +0x72 fp=0xc0000a1ca8 sp=0xc0000a1c58 pc=0x448a72
nginx/unit._Cfunc_GoStringN(...)
	_cgo_gotypes.go:90
nginx/unit.nxt_go_request_add_header(0xc0000ea6c0, 0x7ffd5ddc0dd0, 0x7ffd5ddc0de0)
	/vagrant/src/unit/go/src/nginx/unit/request.go:104 +0x51 fp=0xc0000a1d28 sp=0xc0000a1ca8 pc=0x657bd1
nginx/unit._cgoexpwrap_88d9ae0d83fb_nxt_go_request_add_header(0xc0000ea6c0, 0x7ffd5ddc0dd0, 0x7ffd5ddc0de0)
	_cgo_gotypes.go:314 +0x3f fp=0xc0000a1d50 sp=0xc0000a1d28 pc=0x65667f
runtime.call32(0x0, 0x7ffd5ddc0cd0, 0x7ffd5ddc0d60, 0x18)
	/usr/local/go/src/runtime/asm_amd64.s:519 +0x3b fp=0xc0000a1d80 sp=0xc0000a1d50 pc=0x458d8b
runtime.cgocallbackg1(0x0)
	/usr/local/go/src/runtime/cgocall.go:314 +0x177 fp=0xc0000a1df8 sp=0xc0000a1d80 pc=0x406ad7
runtime.cgocallbackg(0x0)
	/usr/local/go/src/runtime/cgocall.go:191 +0xc5 fp=0xc0000a1e60 sp=0xc0000a1df8 pc=0x4068c5
runtime.cgocallback_gofunc(0x40678f, 0x6591b0, 0xc0000a1ef0, 0xb3c0c0)
	/usr/local/go/src/runtime/asm_amd64.s:773 +0x9b fp=0xc0000a1e80 sp=0xc0000a1e60 pc=0x45a35b
runtime.asmcgocall(0x6591b0, 0xc0000a1ef0)
	/usr/local/go/src/runtime/asm_amd64.s:620 +0x42 fp=0xc0000a1e88 sp=0xc0000a1e80 pc=0x45a1f2
runtime.cgocall(0x6591b0, 0xc0000a1ef0, 0x0)
	/usr/local/go/src/runtime/cgocall.go:131 +0x7f fp=0xc0000a1ec0 sp=0xc0000a1e88 pc=0x40678f
nginx/unit._Cfunc_nxt_cgo_run(0xc0000a1f38, 0x0)
	_cgo_gotypes.go:202 +0x49 fp=0xc0000a1ef0 sp=0xc0000a1ec0 pc=0x656019
nginx/unit.ListenAndServe(0x6f7c31, 0x6, 0x754d00, 0xb3c0c0, 0x70c080, 0x15)
	/vagrant/src/unit/go/src/nginx/unit/unit.go:95 +0x3b fp=0xc0000a1f28 sp=0xc0000a1ef0 pc=0x65837b
main.main()
	/vagrant/src/hello-unit-container/hello.go:19 +0xda fp=0xc0000a1f98 sp=0xc0000a1f28 pc=0x6588ea
runtime.main()
	/usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc0000a1fe0 sp=0xc0000a1f98 pc=0x4307fc
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0000a1fe8 sp=0xc0000a1fe0 pc=0x45aaa1

goroutine 22 [syscall]:
nginx/unit._Cfunc_nxt_cgo_request_done(0x11f8f90, 0x0)
	_cgo_gotypes.go:112 +0x45
nginx/unit.(*request).done(0xc0000ea360)
	/vagrant/src/unit/go/src/nginx/unit/request.go:55 +0x56
nginx/unit.nxt_go_request_handler.func1(0x754d00, 0xb3c0c0, 0xc0000ea360)
	/vagrant/src/unit/go/src/nginx/unit/request.go:142 +0x70
created by nginx/unit.nxt_go_request_handler
	/vagrant/src/unit/go/src/nginx/unit/request.go:140 +0x56

goroutine 24 [syscall]:
nginx/unit._Cfunc_nxt_cgo_request_done(0x11f9190, 0x0)
	_cgo_gotypes.go:112 +0x45
nginx/unit.(*request).done(0xc0000ea5a0)
	/vagrant/src/unit/go/src/nginx/unit/request.go:55 +0x56
nginx/unit.nxt_go_request_handler.func1(0x754d00, 0xb3c0c0, 0xc0000ea5a0)
	/vagrant/src/unit/go/src/nginx/unit/request.go:142 +0x70
created by nginx/unit.nxt_go_request_handler
	/vagrant/src/unit/go/src/nginx/unit/request.go:140 +0x56
2019/09/10 08:10:42 [notice] 24116#24116 process 24134 exited with code 2
2019/09/10 08:10:42 [notice] 24116#24116 initgroups(nobody, 65534) failed (1: Operation not permitted), ignored
2019/09/10 08:10:42 [info] 24142#24142 "hello" application started
2019/09/10 08:10:42 [notice] 24142#24142 setgid(65534) failed (1: Operation not permitted), ignored
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f725adfdfc0 pc=0x65a76f]

runtime stack:
runtime.throw(0x7034ea, 0x2a)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 2612 [syscall]:
runtime.cgocall(0x659070, 0xc000145f58, 0xc0003f8780)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000145f28 sp=0xc000145ef0 pc=0x40676b
nginx/unit._Cfunc_nxt_cgo_request_done(0x2592f90, 0x0)
	_cgo_gotypes.go:112 +0x45 fp=0xc000145f58 sp=0xc000145f28 pc=0x655b55
nginx/unit.(*request).done(0xc0004498c0)
	/vagrant/src/unit/go/src/nginx/unit/request.go:55 +0x56 fp=0xc000145f88 sp=0xc000145f58 pc=0x657836
nginx/unit.nxt_go_request_handler.func1(0x754d00, 0xb3c0c0, 0xc0004498c0)
	/vagrant/src/unit/go/src/nginx/unit/request.go:142 +0x70 fp=0xc000145fc8 sp=0xc000145f88 pc=0x658530
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000145fd0 sp=0xc000145fc8 pc=0x45aaa1
created by nginx/unit.nxt_go_request_handler
	/vagrant/src/unit/go/src/nginx/unit/request.go:140 +0x56

goroutine 1 [runnable, locked to thread]:
nginx/unit._Cfunc_nxt_cgo_run(0xc0000a1f38, 0x0)
	_cgo_gotypes.go:202 +0x49
nginx/unit.ListenAndServe(0x6f7c31, 0x6, 0x754d00, 0xb3c0c0, 0x70c080, 0x15)
	/vagrant/src/unit/go/src/nginx/unit/unit.go:95 +0x3b
main.main()
	/vagrant/src/hello-unit-container/hello.go:19 +0xda
2019/09/10 08:10:52 [notice] 24116#24116 process 24142 exited with code 2
```

```
$ uname -a
Linux ubuntu-bionic 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ go version
go version go1.12.9 linux/amd64
```

I was unable to reproduce this very same crash in debug mode.

**Comment by mar0x** [comment]
Commit 84e4a6437f69b14b1cafbe7915447fdcf1d87f68 should close this issue.
