### ISSUE TITLE
Go-based tests hang indefinitely

### ISSUE THREAD

**Issue by thresheek** [nginx/unit#319]
When launched on the environment where is no `go` binary in $PATH, the tests hang and never return any return code or skip the test or fail the test:

```
thresh@coal nginx/unit/test $ ./run.py                                

2019/09/23 18:02:33 [warn] 11130#11130 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:33 [info] 11130#11130 unit started
Unit has no python module(s)
skipped ''

2019/09/23 18:02:33 [warn] 11136#11136 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:33 [info] 11136#11136 unit started
Unit has no python module(s)
skipped ''

2019/09/23 18:02:33 [warn] 11142#11142 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:33 [info] 11142#11142 unit started
ERROR

2019/09/23 18:02:33 [warn] 11149#11149 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:33 [info] 11149#11149 unit started
ERROR

2019/09/23 18:02:33 [warn] 11155#11155 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:33 [info] 11155#11155 unit started
Unit has no python module(s)
skipped ''

2019/09/23 18:02:34 [warn] 11161#11161 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:34 [info] 11161#11161 unit started
Unit has no java module(s)
skipped ''

2019/09/23 18:02:34 [warn] 11167#11167 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:34 [info] 11167#11167 unit started
Unit has no java module(s)
skipped ''

2019/09/23 18:02:34 [warn] 11173#11173 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:34 [info] 11173#11173 unit started
Unit has no node module(s)
skipped ''

2019/09/23 18:02:34 [warn] 11179#11179 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:34 [info] 11179#11179 unit started
Unit has no node module(s)
skipped ''

2019/09/23 18:02:35 [warn] 11196#11196 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:35 [info] 11196#11196 unit started
Unit has no perl module(s)
skipped ''

2019/09/23 18:02:35 [warn] 11202#11202 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:35 [info] 11202#11202 unit started
Unit has no php module(s)
skipped ''

2019/09/23 18:02:35 [warn] 11208#11208 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:35 [info] 11208#11208 unit started
Unit has no php module(s)
skipped ''

2019/09/23 18:02:35 [warn] 11215#11215 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:35 [info] 11215#11215 unit started
Unit has no python module(s)
skipped ''

2019/09/23 18:02:35 [warn] 11221#11221 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:35 [info] 11221#11221 unit started
Unit has no python module(s)
skipped ''

2019/09/23 18:02:36 [warn] 11227#11227 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:36 [info] 11227#11227 unit started
Unit has no python module(s)
skipped ''

2019/09/23 18:02:36 [warn] 11233#11233 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:36 [info] 11233#11233 unit started
Unit has no python module(s)
skipped ''

2019/09/23 18:02:36 [warn] 11240#11240 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:36 [info] 11240#11240 unit started
Unit has no python module(s)
skipped ''

2019/09/23 18:02:36 [warn] 11246#11246 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:36 [info] 11246#11246 unit started
Unit has no python, openssl module(s)
skipped ''

2019/09/23 18:02:36 [warn] 11254#11254 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:36 [info] 11254#11254 unit started
Unit has no ruby module(s)
skipped ''

2019/09/23 18:02:37 [warn] 11260#11260 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:37 [info] 11260#11260 unit started
Unit has no python module(s)
skipped ''

2019/09/23 18:02:37 [warn] 11266#11266 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:37 [info] 11266#11266 unit started
test_static_etag (test_static.TestStatic) ... 
2019/09/23 18:02:37 [warn] 11272#11272 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:37 [info] 11272#11272 unit started
ok
test_static_head (test_static.TestStatic) ... 
2019/09/23 18:02:37 [warn] 11286#11286 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:37 [info] 11286#11286 unit started
ok
test_static_index (test_static.TestStatic) ... 
2019/09/23 18:02:37 [warn] 11300#11300 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:37 [info] 11300#11300 unit started
ok
test_static_large_file (test_static.TestStatic) ... 
2019/09/23 18:02:38 [warn] 11314#11314 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:38 [info] 11314#11314 unit started
ok
test_static_mime_types (test_static.TestStatic) ... 
2019/09/23 18:02:38 [warn] 11328#11328 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:38 [info] 11328#11328 unit started
ok
test_static_mime_types_correct (test_static.TestStatic) ... 
2019/09/23 18:02:38 [warn] 11342#11342 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:38 [info] 11342#11342 unit started
ok
test_static_mime_types_invalid (test_static.TestStatic) ... skipped 'not yet'
test_static_mime_types_partial_match (test_static.TestStatic) ... 
2019/09/23 18:02:38 [warn] 11356#11356 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:38 [info] 11356#11356 unit started
ok
test_static_mime_types_reconfigure (test_static.TestStatic) ... 
2019/09/23 18:02:39 [warn] 11371#11371 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:39 [info] 11371#11371 unit started
ok
test_static_redirect (test_static.TestStatic) ...
2019/09/23 18:02:39 [warn] 11385#11385 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:39 [info] 11385#11385 unit started
ok
test_static_space_in_name (test_static.TestStatic) ...
2019/09/23 18:02:39 [warn] 11403#11403 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:39 [info] 11403#11403 unit started
файл
ok
test_static_two_clients (test_static.TestStatic) ...
2019/09/23 18:02:39 [warn] 11417#11417 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:39 [info] 11417#11417 unit started
ok

2019/09/23 18:02:39 [warn] 11431#11431 Unit is running unprivileged, then it cannot use arbitrary user and group.
2019/09/23 18:02:39 [info] 11431#11431 unit started
Unit has no python, openssl module(s)
skipped ''

======================================================================
ERROR: setUpClass (test_go_application.TestGoApplication)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/thresh/projects/nginx/unit/test/unit/applications/lang/go.py", line 15, in setUpClass
    if go_app.prepare_env('empty', 'app').returncode == 0:
  File "/home/thresh/projects/nginx/unit/test/unit/applications/lang/go.py", line 34, in prepare_env
    env=env,
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'go': 'go'

======================================================================
ERROR: setUpClass (test_go_isolation.TestGoIsolation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/thresh/projects/nginx/unit/test/test_go_isolation.py", line 15, in setUpClass
    unit = super().setUpClass(complete_check=False)
  File "/home/thresh/projects/nginx/unit/test/unit/applications/lang/go.py", line 15, in setUpClass
    if go_app.prepare_env('empty', 'app').returncode == 0:
  File "/home/thresh/projects/nginx/unit/test/unit/applications/lang/go.py", line 34, in prepare_env
    env=env,
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'go': 'go'

----------------------------------------------------------------------
Ran 12 tests in 6.478s

FAILED (errors=2, skipped=20)
```
Had to hit Ctrl-C at this moment.

```
thresh@coal nginx/unit/test $ whereis go
go:
```
$GOPATH is unset, no go packages installed at all.

**Comment by tiago4orion** [comment]
The diff below solves this:

```
diff --git a/test/unit/applications/lang/go.py b/test/unit/applications/lang/go.py
index 15ac1cd..b8780c0 100644
--- a/test/unit/applications/lang/go.py
+++ b/test/unit/applications/lang/go.py
@@ -10,10 +10,13 @@ class TestApplicationGo(TestApplicationProto):
 
         # check go module
 
-        go_app = TestApplicationGo()
-        go_app.testdir = unit.testdir
-        if go_app.prepare_env('empty', 'app').returncode == 0:
-            cls.available['modules']['go'] = []
+        try:
+            go_app = TestApplicationGo()
+            go_app.testdir = unit.testdir
+            if go_app.prepare_env('empty', 'app').returncode == 0:
+                cls.available['modules']['go'] = []
+        except:
+            pass
```

My python skills are very limited. @andrey-zelenkov does this makes sense?

**Comment by andrey-zelenkov** [comment]
@tiago4orion  You have a pretty good python skills! In this case, it will be better to move `Popen()` call inside `try-except` block (like it was done [before refactoring](https://github.com/nginx/unit/commit/65ca2d7b198bf573fe3caf5e75bf6bd3a172820b#diff-5a5c3d67252b1d56f7964986450e3757L144)). And also add similar block for Java application:
```diff --git a/test/unit/applications/lang/go.py b/test/unit/applications/lang/go.py
--- a/test/unit/applications/lang/go.py
+++ b/test/unit/applications/lang/go.py
@@ -23,18 +23,23 @@ class TestApplicationGo(TestApplicationP
 
         env = os.environ.copy()
         env['GOPATH'] = self.pardir + '/go'
-        process = Popen(
-            [
-                'go',
-                'build',
-                '-o',
-                self.testdir + '/go/' + name,
-                self.current_dir + '/go/' + script + '/' + name + '.go',
-            ],
-            env=env,
-        )
 
-        process.communicate()
+        try:
+            process = Popen(
+                [
+                    'go',
+                    'build',
+                    '-o',
+                    self.testdir + '/go/' + name,
+                    self.current_dir + '/go/' + script + '/' + name + '.go',
+                ],
+                env=env,
+            )
+
+            process.communicate()
+
+        except:
+            pass
 
         return process
 
diff --git a/test/unit/applications/lang/java.py b/test/unit/applications/lang/java.py
--- a/test/unit/applications/lang/java.py
+++ b/test/unit/applications/lang/java.py
@@ -63,8 +63,12 @@ class TestApplicationJava(TestApplicatio
             ]
             javac.extend(src)
 
-            process = Popen(javac)
-            process.communicate()
+            try:
+                process = Popen(javac)
+                process.communicate()
+
+            except:
+                self.fail('Cann\'t run javac process.')
 
         self._load_conf(
             {
```

Going to check and commit this tomorrow
