### ISSUE TITLE
Ruby example

### ISSUE THREAD

**Issue by pilot87** [nginx/unit#342]
I am using ruby example
/site/rb/app.rb:
```ruby
app = Proc.new do |env|
    ["200", {
        "Content-Type" => "text/plain",
    }, ["Hello, Unit!"]]
end

run app
```
config.json:
```json
...
"stub.rb": {
            "type": "ruby",
            "processes": {
                "max": 10,
                "spare": 2,
                "idle_timeout": 20
            },
            "script": "/site/rb/app.rb",
            "working_directory": "/site/rb/"
        }
...
```
but UNIT return error:
```console
 curl -X PUT -d @/site/_config.json 'http://localhost:8080/config/'
{
        "error": "Failed to apply new configuration."
}
```
sudo cat /var/log/unit.log:
```console
2019/11/07 11:21:44 [alert] 9810#9810 Ruby: Failed to parse rack script
2019/11/07 11:21:44 [alert] 9810#9810 Ruby: /site/rb/app.rb:7:in `<top (required)>': \
undefined method `run' for main:Object (NoMethodError)
```

**Comment by pilot87** [comment]
I've try to use "call" method, but things still not going well:
app.rb:
```ruby
app = Proc.new do |env|
    ["200", {
        "Content-Type" => "text/plain",
    }, ["Hello, Unit!"]]
end

app.call
```
/var/log/unit.d:
```console
2019/11/07 12:43:36 [info] 10035#10035 "ruby_app" application started
2019/11/07 12:43:36 [alert] 10035#10035 Ruby: Failed to parse rack script
2019/11/07 12:43:36 [alert] 10035#10035 Ruby: /usr/lib/ruby/vendor_ruby/rack/builder.rb:43:in `parse_file': uninitialized constant App (NameError)
2019/11/07 12:43:36 [notice] 535#535 process 10035 exited with code 1
2019/11/07 12:43:36 [warn] 538#538 failed to start application "ruby_app"
2019/11/07 12:43:36 [alert] 538#538 failed to apply new conf
2019/11/07 12:43:36 [notice] 535#535 process 10033 exited with code 0
2019/11/07 12:43:36 [notice] 535#535 process 10034 exited with code 0
```

**Comment by VBart** [comment]
It's a `rackup` script. See: https://rack.github.io/

Ruckup scripts use some kind of DSL and must have `.ru` file extension to be parsed correctly by the Ruby interpreter.

**Comment by pilot87** [comment]
I've done renaming and installed rack but config still foulting:
```console
2019/11/07 15:23:25 [info] 540#540 "ruby_app" application started
2019/11/07 15:23:25 [alert] 540#540 Ruby: Failed to parse rack script
2019/11/07 15:23:25 [alert] 540#540 Ruby: /usr/lib/ruby/vendor_ruby/rack/builder.rb:43 \
:in `parse_file': uninitialized constant App (NameError)
```
Do I need to install RoR also or something else?
I am so nooby in administering web servers... :)

**Comment by mar0x** [comment]
Make sure you installed **rack** using `gem install rack`.

**Comment by VBart** [comment]
@pilot87 You can't do `app.call` until the app will be initialized by the Rack builder. Does it work if you revert the example back to
```
app = Proc.new do |env|
    ["200", {
        "Content-Type" => "text/plain",
    }, ["Hello, Unit!"]]
end

run app
```
?

**Comment by pilot87** [comment]
@VBart @mar0x thank you wary match! It start to work after ruby gems updating was made

**Comment by pilot87** [comment]
@VBart @mar0x thank you wary match! It start to work after ruby gems updating was made
(I have debian 9 distro)
```console
>>> uname -a
Linux ip-*masked* 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux
```
