### ISSUE TITLE
1.16 issue?

### ISSUE THREAD

**Issue by smtalk** [nginx/unit#413]
I've just updated to 1.16, but I'm getting hangs with:
curl --unix-socket /var/run/unit/control.sock 'http://localhost/config/'

Log just has:
2020/03/12 21:33:45.805 [alert] 18262#18262 [unit] version check error

Downgrading to 1.15 solves the issue.

I've tested it multiple times with the same result. I'm going to debug it deeper, just reporting it now, as timing might be important if that's a bug.

**Comment by mar0x** [comment]
If you have Node.js or Go applications you need to update modules manually.

**Comment by smtalk** [comment]
@mar0x Go is a 'compiled' application (executable), "make go-install" was done, but it should have nothing to do with it... Does it mean golang applications (executables) need to be recompiled every time unit is updated?

**Comment by VBart** [comment]
@smtalk Your Go application is compiled to work with Unit 1.15. In order to run it using Unit 1.16, you have to recompile it with Unit 1.16 sources and library.

**Comment by smtalk** [comment]
@VBart wouldn't it make sense to 'skip' incompatible applications from loading and log this event, instead of 'hanging' the calls?

Is there a plan to make some backwards compatibility in the future? We're still testing Unit, but we've planned to offer "go" for shared web hosting, it seems it'll be difficult to do so, because update of Unit would break the environment up.

Regarding nodejs - I guess it's just a matter of "npm install -g --unsafe-perm unit-http", so their applications would still be running after this, right?

**Comment by smtalk** [comment]
@mar0x I guess NodeJS behaves differently (and just needs "npm install -g --unsafe-perm unit-http" after update of unit). But breaking whole unit just after a simple (and likely automatic) "yum update" is a huge issue, isn't it? Maybe there are plans to re-do the Go part in Unit? For example, make Go apps to have a 'socket' (UDS) listener and interact with it.. or just make the library backwards compatible, I mean if go app is compiled, it could still be portable and work with never unit versions.

Else "unit" should have source of go app defined and 're-compile' automatically after update time... Sounds really messy :)

**Comment by tiago4orion** [comment]
> Is there a plan to make some backwards compatibility in the future? We're still testing Unit, but we've planned to offer "go" for shared web hosting, it seems it'll be difficult to do so, because update of Unit would break the environment up.

We plan to fix that (not replying from the controller API). I recommend for now just set a timeout in the HTTP request.

> For example, make Go apps to have a 'socket' (UDS) listener and interact with it.. or just make the library backwards compatible, I mean if go app is compiled, it could still be portable and work with never unit versions.

This should be fixed, for sure.

**Comment by smtalk** [comment]
That's a very serious issue.. Whole nginx unit configuration got discarded just because of node update as well:
`2020/11/21 11:34:29 [alert] 17198#17198 [unit] version check error
/home/admin/domains/aaba.com/testapp/node_modules/unit-http/http_server.js:416
    this.unit.createServer();
              ^
Error: Failed to create Unit object
    at new Server (/home/admin/domains/aaba.com/testapp/node_modules/unit-http/http_server.js:416:15)
    at Object.createServer (/home/admin/domains/aaba.com/testapp/node_modules/unit-http/http.js:13:12)
    at Object.<anonymous> (/home/admin/domains/aaba.com/testapp/app.js:4:4)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47`

I think:
1) if there are any apps that cannot be started, unit could skip these with the same "alert" in logs (and maybe stderr), same with routes. I mean whole server with all applications shouldn't be off just because 1 app is failing to start after nginx unit update.
2) NodeJS/Go should be backwards compatible, and unit updates shouldn't bring them down. Why cannot they simply (optionally, if you don't like the idea) listen on their own socket? User-owned, not readable by anyone else. Maybe that way it'd be easier to make the connection backwards-compatible?

We're integrating Nginx Unit with a shared hosting control panel, and it's a huge problem to find all apps and recompile them. Go ones might even have no source code to compile from on the server... So, at this time it's unusable for Go/NodeJS apps there just because of it (and alternatives like Passenger would still be needed to serve them). No issues with interpreted languages, of course.

Thank you for your time and efforts!

**Comment by VBart** [comment]
1. The configuration is consistent and atomic only as the whole. We can't predict if it's useful or safe to apply and use configuration, receive requests if one of the parts fails. Currently Unit falls back to the default configuration with no listening sockets, so a load-balancer can easily detect that this instance is broken and avoid passing requests to it, because any connection attempts will immediately get RST. If we will start Unit with partially failed configuration, then such detection from the load-balancer side will be much harder, especially if not all requests routed to a broken app.

2. You can configure that. Just make them listen on a socket and configure a "proxy" in Unit. It's not that handy right now, but we are thinking about introducing something like that, where unit will run the app and just proxy requests via a regular socket. On the other hand, we can't just fall back to that mode automatically as there's no guarantee that the app will function the same way, because in this case Node/Go HTTP module will be in use with its own constrains and peculiarities.

> We're integrating Nginx Unit with a shared hosting control panel, and it's a huge problem to find all apps and recompile them. Go ones might even have no source code to compile from on the server... So, at this time it's unusable for Go/NodeJS apps there just because of it (and alternatives like Passenger would still be needed to serve them).

Yes, I understand the problem. Unfortunately, due to the way how these apps are functioning, the support of them in Unit is the most problematic. We're looking for a solution how to avoid the need for modifying source code for Node/Go and how to avoid the need of rebuilding on any update.

Right now, I'd suggest to detect if there's any "external" type apps are configured in Unit and warn the user, that he needs to recompile those apps first.

**Comment by smtalk** [comment]
@VBart may I ask you what's the priority of this issues? (months or years until it's checked?) We'd like to plan the things a bit, and if it's "months" case - we'd still be ready to use Unit to serve go and/or node there :) Thanks!

**Comment by VBart** [comment]
@smtalk Since we don't see much interest from Go/Node.js community in Unit (currently it feels like the least used modules) and taking into account that a proper solution can be very complicated, so right now I can't promise any ETA for that. But probably it's a сhicken-and-egg issue: low interest because of low usability. I'd say it looks like a good goal for 2021.
