### ISSUE TITLE
Enhanced restriction of option value

### ISSUE THREAD

**Issue by hongzhidao** [nginx/unit#451]
Hi.

```
diff --git a/src/nxt_conf_validation.c b/src/nxt_conf_validation.c
index a5e0663..69d7a7e 100644
--- a/src/nxt_conf_validation.c
+++ b/src/nxt_conf_validation.c
@@ -2444,7 +2444,7 @@ nxt_conf_vldt_server_weight(nxt_conf_validation_t *vldt,

     num_value = nxt_conf_get_number(value);

-    if (num_value < 0) {
+    if (num_value <= 0) {
         return nxt_conf_vldt_error(vldt, "The \"weight\" number must be "
                                    "positive.");
     }
```
And I found some other options such as `header_read_timeout`, `max_body_size`, etc are allowed to set non-positive value.
They are converted to unsigned integers.
Consider improving their restrictions if they are not the original intention.

**Comment by VBart** [comment]
Zero "weight" is perfectly fine and quite useful to remove traffic from a server completely if there are other servers alive.

Please always run functional tests for the changes. If you had run them in this case, you'd have realized that it was intentional:
```
% python test/test_upstreams_rr.py
.........Path to unit.log:
/tmp/unit-test-fphcj4dz/unit.log

F..Path to unit.log:
/tmp/unit-test-z9sw6d1n/unit.log

F
======================================================================
FAIL: test_upstreams_rr_servers_empty (__main__.TestUpstreamsRR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_upstreams_rr.py", line 526, in test_upstreams_rr_servers_empty
    'configure servers empty one',
AssertionError: 'success' not found in {'error': 'Invalid configuration.', 'detail': 'The "weight" number must be positive.'} : configure servers empty one

======================================================================
FAIL: test_upstreams_rr_weight_rational (__main__.TestUpstreamsRR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_upstreams_rr.py", line 206, in test_upstreams_rr_weight_rational
    check_weights(0, 1)
  File "test/test_upstreams_rr.py", line 203, in check_weights
    set_weights(w1, w2)
  File "test/test_upstreams_rr.py", line 194, in set_weights
    'configure weights',
AssertionError: 'success' not found in {'error': 'Invalid configuration.', 'detail': 'The "weight" number must be positive.'} : configure weights

----------------------------------------------------------------------
Ran 13 tests in 6.743s

FAILED (failures=2)
```

What can really be improved here is the error message: "The weight number must not be negative".

**Comment by hongzhidao** [comment]
> What can really be improved here is the error message: "The weight number must not be negative".

Agree.

Just remind that the diff I showed is used to express the problem.
