### ISSUE TITLE
Django 4.0 ASGI lifespan error

### ISSUE THREAD

**Issue by travisbell** [nginx/unit#615]
Hi guys,

I'm completely new to getting Python up and running with Unit and if this is actually just a Django error, please let me know _but_ I did simply follow the docs and am seeing the below error on a completely fresh Python 3.10 + Django 4.0 app:

```
2021/12/09 18:17:56 [info] 233#233 "python" application started
2021/12/09 18:17:56 [info] 0#233 [unit] ASGI Lifespan processing exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/asgi.py", line 143, in __call__
    raise ValueError(
ValueError: Django can only handle ASGI/HTTP connections, not lifespan.
2021/12/09 18:17:56 [info] 233#234 [unit] ASGI Lifespan processing exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/asgi.py", line 143, in __call__
    raise ValueError(
ValueError: Django can only handle ASGI/HTTP connections, not lifespan.
```

Is this a Unit problem, or a Django problem? Django 4.0 was just released so maybe it's just a compatibility problem with 4.0?

Starting Unit with the `wsgi` handler works fine, no errors. Config is simple:

```
"python": {
  "type": "python",
  "path": "/path/to/project/django_example",
  "module": "django_example.asgi",
  "callable": "application"
}
```

Thanks!

**Comment by travisbell** [comment]
Ok, great, I didn't realize the error was nothing to worry about. If it's nothing to be concerned about, I would agree, perhaps that should only log on debug.

> Btw, does your ASGI application works as expected (except the lifespan messages)?

Yes, it seems to. Nothing to worry about then.

Thanks for the quick reply.

**Comment by archatas** [comment]
Today I experienced the same error too and Django `django/core/handlers/asgi.py` raised an error around these lines:

```python
if scope["type"] != "http":
            raise ValueError(
                "Django can only handle ASGI/HTTP connections, not %s." % scope["type"]
            )
```

Is there anything in Nginx Unit configuration that I could change to change the scope type to "http"?
