### ISSUE TITLE
Ruby NGINX_Unit_Stream_IO_Error

### ISSUE THREAD

**Issue by travisbell** [nginx/unit#654]
When starting up a completely empty Sinatra app, we get the following error:

```
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: Ruby: /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/2.7.0/logger/log_device.rb:95:in `initialize': no implicit conversion of NGINX_Unit_Stream_IO_Error into String (TypeError)
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/2.7.0/logger/log_device.rb:95:in `open'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/2.7.0/logger/log_device.rb:95:in `open_logfile'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/2.7.0/logger/log_device.rb:86:in `set_dev'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/2.7.0/logger/log_device.rb:18:in `initialize'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/2.7.0/logger.rb:389:in `new'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/2.7.0/logger.rb:389:in `initialize'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/logger.rb:13:in `new'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/logger.rb:13:in `call'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:255:in `call'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:248:in `call'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:218:in `call'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1992:in `call'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `block in call'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1768:in `synchronize'
2022/02/23 14:40:47 [error] 14030#5942506 [unit] #8: from /Users/travisbell/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `call'
```

This is very easy to reproduce:

### Gemfile

```ruby
source "https://rubygems.org"

gem "sinatra"
```

### config.ru

```ruby
# frozen_string_literal: true

require 'bundler'
Bundler.require

get '/', :provides => 'json' do
  { :path => "/" }.to_json
end

run Sinatra::Application
```

### unit_config.json

```json
{
  "listeners": {
    "*:9088": {
      "pass": "routes/app"
    }
  },
  "routes": {
    "app": [
      {
        "action": {
          "pass": "applications/app"
        }
      }
    ]
  },
  "applications": {
    "app": {
      "type": "ruby",
      "processes": 1,
      "script": "config.ru",
      "working_directory": "/path/to/directory/",
    }
  }
}
```

No other Ruby web servers have an issue with this simple example, Puma, Iodine and Thin for example, all work properly.

**Comment by hongzhidao** [comment]
@travisbell 
Seems it has something to do with missed logging.

1. from the rack spec, the `rack.logger` is not required.
https://github.com/rack/rack/blob/main/SPEC.rdoc

2. `Sinatra` allows you to define custom logging.
http://sinatrarb.com/contrib/custom_logger

My suggestion is to disable logging or defined custom logging by yourself.
For example:
```
require 'sinatra'

configure do
    set :logging, nil
end

get '/' do
    'Hello World'
end

run Sinatra::Application
```

We'll discuss if there is a better solution.

**Comment by travisbell** [comment]
Hi @hongzhidao, thanks.

Yes, we can certainly set a nil logger but I thought I'd mention this since a "clean" and out of the box Sinatra app fails in Unit when it doesn't in any other server. This could be a deterrent for someone trying to migrate an app since they might not understand what's going on.

**Comment by hongzhidao** [comment]
@travisbell 
>I thought I'd mention this since a "clean" and out of the box Sinatra app fails in Unit when it doesn't in any other server.

It makes sense.

Since Unit supports more than Ruby, compared to STDOUT (rb_stderr), `rack.errors` defined custom error log format for `unit.log`. such as 
```
2022/03/09 01:48:12 [error] 188373#188373 [unit] #8: Ruby: 127.0.0.1 - - [09/Mar/2022:01:48:12 +0800] "GET config.ru/ HTTP/1.1" 200 11 0.0025
```
The Ruby module implements `rack.input` and `rack.errors` streams.
And users can do like below by `rack.errors`:
```
app = Proc.new do |env|
    env['rack.errors'].puts('Error in application')
    ['200', {'Content-Length' => '0'}, ['']]
end

run app
```

Previously, Unit throws the above errors because of the missing define `close` in streams on Sinatra apps.
Note Sinatra has its own exception handling.
```
    def set_dev(log)
      if log.respond_to?(:write) and log.respond_to?(:close)
        @dev = log
      else
        @dev = open_logfile(log)
        @dev.sync = true
        @filename = log
      end
    end

    def open_logfile(filename)
      begin
        File.open(filename, (File::WRONLY | File::APPEND))
"/usr/share/ruby/logger.rb" line 735 of 855 --85%-- col
 7
```

Here's the patch, welcome to test :)
https://gist.github.com/hongzhidao/be40b40a88800869e7510f84b81640a1

**Comment by travisbell** [comment]
@hongzhidao This looks much better, yes! 👍🏼
