### ISSUE TITLE
django3.2 app process exited

### ISSUE THREAD

**Issue by Sunnnner** [nginx/unit#661]
- my settings:
```json
{
  "applications": {
    "kws": {
      "type": "python 3.8",
      "user": "nobody",
      "processes": {
        "max": 4,
        "spare": 1,
        "idle_timeout": 60
      },
      "path": "/demo",
      "module": "demo.asgi",
      "limits": {
        "timeout": 120,
        "requests": 1000
      }
    }
  },
  "listeners": {
    "*:8000": {
      "application": "demo"
    }
  }
}

```

- error message:
```txt
2022/03/18 05:47:40 [notice] 25#25 app process (isolated 29787) exited with code 0
dj_1             | 2022/03/18 05:47:40 [info] 5788#5788 "demo" application started
dj_1             | 2022/03/18 05:47:40 [info] 0#5788 [unit] ASGI Lifespan processing exception
dj_1             | Traceback (most recent call last):
dj_1             |   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/asgi.py", line 143, in __call__
dj_1             |     raise ValueError(
dj_1             | ValueError: Django can only handle ASGI/HTTP connections, not lifespan.
dj_1             | 2022/03/18 05:47:57 [notice] 25#25 app process (isolated 1006) exited with code 0
dj_1             | 2022/03/18 05:48:00 [info] 9137#9137 "demo" application started
dj_1             | 2022/03/18 05:48:00 [info] 0#9137 [unit] ASGI Lifespan processing exception
dj_1             | Traceback (most recent call last):
dj_1             |   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/asgi.py", line 143, in __call__
dj_1             |     raise ValueError(
dj_1             | ValueError: Django can only handle ASGI/HTTP connections, not lifespan.

```
- Operating environment: `ubuntu20.04 python3.8.10 django3.2` for docker

**Comment by mar0x** [comment]
Hello,
Messages only indicates exactly what it says: "_Django can only handle ASGI/HTTP connections, not lifespan._"
This is not an issue. Your application should process request as expected. WebSocket may not work (see #572) because of https://github.com/django/channels/pull/1577 .

Do you spot any other issues except log messages?

**Comment by Sunnnner** [comment]
> Hello, Messages only indicates exactly what it says: "_Django can only handle ASGI/HTTP connections, not lifespan._" This is not an issue. Your application should process request as expected. WebSocket may not work (see #572) because of [django/channels#1577](https://github.com/django/channels/pull/1577) .
> 
> Do you spot any other issues except log messages?

Thank you for the help!
