### ISSUE TITLE
[unit] versions mismatch: the Unit daemon has version 1.29.0, while the app was compiled with libunit 1.27.0

### ISSUE THREAD

**Issue by rich-wi** [nginx/unit#812]
Hi, 
I was wondering if you could help with this issue I am having. 

Here is a dump of the unit.log

2022/12/19 00:33:24 [info] 1887#1887 discovery started
2022/12/19 00:33:24 [notice] 1887#1887 no modules matching: "/usr/lib/unit/modules/*.unit.so" found
2022/12/19 00:33:24 [info] 1886#1886 controller started
2022/12/19 00:33:24 [notice] 1886#1886 process 1887 exited with code 0
2022/12/19 00:33:24 [info] 1889#1889 router started
2022/12/19 00:33:24 [info] 1889#1889 OpenSSL 3.0.2 15 Mar 2022, 30000020
2022/12/19 00:33:24 [info] 1890#1890 "api" prototype started
2022/12/19 00:33:24 [info] 1891#1891 "api" application started
2022/12/19 00:33:25 [alert] 1891#1891 [unit] versions mismatch: the Unit daemon has version 1.29.0, while the app was compiled with libunit 1.27.0
/root/node_modules/unit-http/http_server.js:406
    this.unit.createServer();
              ^

Error: Failed to create Unit object
    at new Server (/root/node_modules/unit-http/http_server.js:406:15)
    at createServer (/root/node_modules/unit-http/http.js:15:12)
    at Object.serverFactory (/root/api/api.js:18:24)
    at getServerInstance (/root/node_modules/fastify/lib/server.js:273:22)
    at createServer (/root/node_modules/fastify/lib/server.js:15:18)
    at fastify (/root/node_modules/fastify/fastify.js:185:30)
    at Object.<anonymous> (/root/api/api.js:24:31)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)

Node.js v18.4.0
2022/12/19 00:33:25 [notice] 1890#1890 app process 1891 exited with code 1
2022/12/19 00:33:25 [warn] 1889#1889 failed to start application "api"
2022/12/19 00:33:25 [alert] 1889#1889 failed to apply new conf
2022/12/19 00:33:25 [alert] 1888#1888 failed to apply previous configuration
2022/12/19 00:33:25 [notice] 1886#1886 process 1890 exited with code

Is there anyway I can fix the mismatch error?

Thanks!

**Comment by lcrilly** [comment]
Hello. It looks like you upgraded to Unit 1.29.0 but still have an older `unit-http` npm module.

This should be enough to update the module:
```
npm update -g --unsafe-perm unit-http
cd /path/to/node_app
npm link unit-http
```

But do refer to the [docs](https://unit.nginx.org/installation/#installation-nodejs-package).

**Comment by rich-wi** [comment]
Thanks @lcrilly , that was it. Much appeciated!
