### ISSUE TITLE
Seems unit server picking up stale configuration 

### ISSUE THREAD

**Issue by sandeep-gh** [nginx/unit#813]
I reinstalled unit server, launched it and checked the config via 
`doas  curl  --unix-socket  /var/run/unit/control.sock http://localhost/config/`
The output
```
{
        "listeners": {},
        "applications": {}
}

```
shows no listeners or applications are registered. 

However, in the log file I see following error messages:
```
2022/12/20 17:57:08.134 [alert] 73483#616790 Python failed to import module "monalwebworks"
Traceback (most recent call last):
  File "/var/www/htdocs/monalwebworks.in/monalwebworks.py", line 2, in <module>
    import justpy as jp
  File "/var/www/htdocs/monalwebworks.in/justpy/__init__.py", line 2, in <module>
    from .justpy import *
  File "/var/www/htdocs/monalwebworks.in/justpy/justpy.py", line 1, in <module>
    from starlette.applications import Starlette
ModuleNotFoundError: No module named 'starlette'
```

From where is unit trying to load monalwebworks app stored in /var/www/htdocs? Which particular python on the system is it using?
I have turned on the debug but I am not able to find it. 

Any help would be great.

**Comment by sandeep-gh** [comment]
Never mind. I just used -X DELETE to delete all registered apis.
