### ISSUE TITLE
when hosting an starlette app: which python executable is used when loading the app

### ISSUE THREAD

**Issue by sandeep-gh** [nginx/unit#814]
I am loading a starlette app in unit as follows:

```
doas  curl -X PUT --data-binary @/home/shared/launchpad/unit_cfg.json --unix-socket  /var/run/unit/control.sock http://localhost/config/
```
where unit_cfg.json is as follows:
```
  {   
            "listeners": {
                "*:6580": {
                    "pass": "routes"
                }
            },
            
            "routes": [
                {   
                    "action": {
                        "pass": "applications/starlette"
                    }
                }
            ],
            
            "applications": {
                "starlette": {
                    "type": "python 3.11",
                    "path": "/var/www/htdocs/monalwebworks.in/",
                    "home": "/var/www/htdocs/monalwebworks.in/venv/",
                    "module": "monalwebworks",
                    "callable": "app"
                }
            }
        }
```
I have not yet created the virtual environment `/var/www/htdocs/monalwebworks.in/venv/`.
In log file I can see following messages
```
 main start prototype: starlette^@{"type":"python 3.11","path":"/var/www/htdocs/monalwebworks.in/",
"home":"/var/www/htdocs/monalwebworks.in/venv/","module":"monalwebworks","callable":"app"}
2022/12/20 18:37:20.010 [info] 63396#209443 "starlette" application started

```

Then I get the error:
```
2022/12/20 18:37:20.010 [alert] 63396#209443 Python failed to import module "monalwebworks"
Traceback (most recent call last):
  File "/var/www/htdocs/monalwebworks.in/monalwebworks.py", line 2, in <module>
    import justpy as jp
  File "/var/www/htdocs/monalwebworks.in/justpy/__init__.py", line 2, in <module>
    from .justpy import *
  File "/var/www/htdocs/monalwebworks.in/justpy/justpy.py", line 1, in <module>
    from starlette.applications import Starlette
ModuleNotFoundError: No module named 'starlette'

```
 My question is which python environment is being used to load the app. Shouldn't unit give an error saying no file or directory `/var/www/htdocs/monalwebworks.in/venv/`. 

Any pointer would be great. Thanks.

**Comment by sandeep-gh** [comment]
using an updated unit 1.29 worked.
