### ISSUE TITLE
Handshake 502 Bad Gateway when using Websocket over http

### ISSUE THREAD

**Issue by mogarg** [nginx/unit#825]
I have a Django channels and rest api application running using unit. I am able to access the channels sockets using `ws:`, however, if I try to access the same (running proxied in production via `https` link) using `wss:`, I get the following error - 

```
2023/01/10 23:25:50 [error] 217#217 [unit] #450: receive() called for closed WebSocket
2023/01/10 23:25:50 [error] 217#217 [unit] #450: Python failed to call 'future.result()'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/channels/security/websocket.py", line 41, in __call__
    return await denier(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/channels/consumer.py", line 62, in __call__
    await await_many_dispatch([receive], self.dispatch)
  File "/opt/venv/lib/python3.11/site-packages/channels/utils.py", line 51, in await_many_dispatch
    tasks[i] = asyncio.ensure_future(consumer_callables[i]())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: WebSocket already closed
```

Any `https` request to the API is however successful. Any idea what I can do to fix this?

**Comment by tippexs** [comment]
Do you have any configuration and a small python code example to reproduce? I will have a look into it.
