### ISSUE TITLE
 "error": "Failed to apply new configuration."

### ISSUE THREAD

**Issue by robin7245** [nginx/unit#857]
"error": "Failed to apply new configuration."

This is the config.json file:

{
    "listeners": {
        "*:80": {
            "pass": "applications/unit1"
        }
    },

    "applications": {
        "unit1": {
            "type": "java",
            "webapp": "/root/warDir/unit1.war"
        }
    }
}

This is the log data:

2023/04/01 18:14:18 [info] 61952#61952 "unit1" prototype started
2023/04/01 18:14:18 [info] 61953#61953 "unit1" application started
2023/04/01 18:14:18 [alert] 61953#61953 Unhandled exception in application start
Exception in thread "main" java.io.FileNotFoundException: Unable to determine code source archive from /root/warDir/unit1.war
        at nginx.unit.Context.loadApp(Context.java:376)
        at nginx.unit.Context.start(Context.java:344)
2023/04/01 18:14:18 [notice] 61952#61952 app process 61953 exited with code 1
2023/04/01 18:14:18 [warn] 60985#60985 failed to start application "unit1"
2023/04/01 18:14:18 [alert] 60985#60985 failed to apply new conf
2023/04/01 18:14:18 [notice] 60982#60982 process 61952 exited with code 0

The unit1.war exists.
Here is ls command

# ls /root/warDir
unit1.war

**Comment by robin7245** [comment]
warDir and unit1.war permissions are 755.
I am using ubuntu 22.04 and unit 1.29.1

**Comment by lcrilly** [comment]
Hello.

It looks like Unit is reading the **/root/warDir/unit1.war** file just fine, but is unable to get what it needs from there to start the application.

Your configuration is quite minimal for most Java environments. Please try 

1. Setting a `working_directory` https://unit.nginx.org/configuration/#configuration-apps-common
2. Setting `classpath` if you have multiple .jar files https://unit.nginx.org/configuration/#java
3. Set the context path (default is `/` which is unlikely to be what you need)

```json
"applications": {
    "unit1": {
        "type": "java",
        "webapp": "/root/warDir/unit1.war",
        "working_directory": "/root/warDir",
        "classpath": "/root/warDir/foo",
        "options": [ "-Dnginx.unit.context.path=/root/warDir" ]
    }
}
```

**Comment by lcrilly** [comment]
@robin7245 did you have any luck with this?

**Comment by tanjiarui** [comment]
I got the same error, but I actually customized the startup config as follows
```bash
sudo unitd-debug --no-daemon --control 127.0.0.1:8080 --group ubuntu --user ubuntu
```
here is my config file
```json
{
    "listeners": {
        "127.0.0.1:8080": {
            "pass": "applications/fastapi"
        }
    },
    "applications": {
        "fastapi": {
            "type": "python 3.10",
            "path": "/home/ubuntu/test",
            "home": "/home/ubuntu/test/env",
            "module": "asgi",
            "callable": "app:app"
        }
    }
}
```
this is the curl command
```curl
sudo curl -X PUT --data-binary @unit.config http://localhost:8080/config
```

**Comment by lcrilly** [comment]
@tanjiarui the problem post is specific to Java. You might have the same error message from Unit but it is not the same issue. Please create a new issue for your problem.
